apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: testvs
  namespace: default
spec:
  hosts:
  - "bla.knative.acc.transpose-it.nl"
  gateways:
  - knative-serving/knative-ingress-gateway
  - knative-serving/cluster-local-gateway
  - istio-system/ingressgateway
  - mesh # applies to all the sidecars in the mesh
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: test123.default.svc.cluster.local
        port:
          number: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test-destinationrule
  namespace: default
spec:
  host: test123.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN


---
apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: test123 # The name of the app
  namespace: default # The namespace the app will use
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go # The URL to the image of the app
          env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "Go Sample v1"
